### PR TITLE
Remove return when retry exceeds 5

### PR DESCRIPTION
**Pull request by psihius**
Well, we still got issues after a while and it does seem that RCON has a throughput limit - so retries still piled up.

But the problem is that when retries are above 5 - WE HAVE A FREAKING EXIT! After that, it just exits the block all the time and never gets back into the body of the if afterwards. So a small bump creates a permanent blockage :)

After removing this - it takes like up to 7-8 retries on Nexus production to pile up and the whole thing gets cleared in milliseconds once the pipe gets freed up.
Mostly pileups happen when the node gets train teleporting data or a player joins the game and it blocks rcon execution (or there is data transfer spike).
See debug log below. I leave that running on Nexus prod till this gets merged and people can see it live.

```Pooling on 1
Done, pulled ; try 1
Reseting timer try 1
Exited the loop
Pooling on 1
Done, pulled ; try 1
Reseting timer try 1
Exited the loop
Fact: 603.231 Warning ServerSynchronizer.cpp:375: Peer 14 sent IncreasedLatencyConfirm for tick 9712514, but it is too late as I'm processing his tick 9712515
Clusterio | playerManager | 603.231 Warning ServerSynchronizer.cpp:375: Peer 14 sent IncreasedLatencyConfirm for tick 9712514, but it is too late as I'm processing his tick 9712515
Pooling on 1
Done, pulled ; try 1
Reseting timer try 1
Exited the loop
got trainstops from master
Pooling on 1
Done, pulled ; try 1
Reseting timer try 1
Exited the loop
Fact: 606.746 Info ServerMultiplayerManager.cpp:925: updateTick(9712718) received stateChanged peerID(16) oldState(ConnectedDownloadingMap) newState(ConnectedLoadingMap)
Clusterio | playerManager | 606.746 Info ServerMultiplayerManager.cpp:925: updateTick(9712718) received stateChanged peerID(16) oldState(ConnectedDownloadingMap) newState(ConnectedLoadingMap)
Pooling on 1
Done, pulled ; try 1
Reseting timer try 1
Exited the loop
Pooling on 1
got trainstops from master
{ ok: false, msg: 'Invalid request parameters' }
Done, pulled ; try 1
Reseting timer try 1
Exited the loop
Fact: 610.765 Info ServerMultiplayerManager.cpp:925: updateTick(9712959) received stateChanged peerID(16) oldState(ConnectedLoadingMap) newState(TryingToCatchUp)
Clusterio | playerManager | 610.765 Info ServerMultiplayerManager.cpp:925: updateTick(9712959) received stateChanged peerID(16) oldState(ConnectedLoadingMap) newState(TryingToCatchUp)
Pooling on 1
Pooling on 2
Clusterio | trainTeleports | {"event":"trainstop_removed","name":"<C> bassmans","x":"-133","y":"33","surface":"nauvis"}
Clusterio | trainTeleports | Removing trainstop <C> bassmans at x:-133 y:33
got trainstops from master
Clusterio | trainTeleports | {"event":"trainstop_removed","name":"<C> Kieran Uttley","x":"-127","y":"33","surface":"nauvis"}
Clusterio | trainTeleports | Removing trainstop <C> Kieran Uttley at x:-127 y:33
got trainstops from master
Pooling on 3
Fact: 618.163 Info ServerMultiplayerManager.cpp:925: updateTick(9713403) received stateChanged peerID(16) oldState(TryingToCatchUp) newState(WaitingForCommandToStartSendingTickClosures)
Clusterio | playerManager | 618.163 Info ServerMultiplayerManager.cpp:925: updateTick(9713403) received stateChanged peerID(16) oldState(TryingToCatchUp) newState(WaitingForCommandToStartSendingTickClosures)
Fact: 618.163 Info GameActionHandler.cpp:4082: UpdateTick (9713403) processed PlayerJoinGame peerID(16) playerIndex(749) mode(connect)
Clusterio | playerManager | 618.163 Info GameActionHandler.cpp:4082: UpdateTick (9713403) processed PlayerJoinGame peerID(16) playerIndex(749) mode(connect)
Pooling on 4
Fact: 618.366 Info ServerMultiplayerManager.cpp:925: updateTick(9713416) received stateChanged peerID(16) oldState(WaitingForCommandToStartSendingTickClosures) newState(InGame)
Clusterio | playerManager | 618.366 Info ServerMultiplayerManager.cpp:925: updateTick(9713416) received stateChanged peerID(16) oldState(WaitingForCommandToStartSendingTickClosures) newState(InGame)
Fact: 2019-07-15 01:22:33 [JOIN] Aronak joined the game
Clusterio | playerManager | 2019-07-15 01:22:33 [JOIN] Aronak joined the game
Pooling on 5
Warning: Inventory syncing slow. Tries: 6
Pooling on 6
Warning: Inventory syncing slow. Tries: 7
Pooling on 7
Warning: Inventory syncing slow. Tries: 8
Pooling on 8
Done, pulled Aronak
; try 8
Syncing: Aronak try 8
isBanned?: Aronak try 8
isBanned done: Aronak try 8
getPlayer: Aronak try 8
getPlayer done: Aronak try 8
Going player data try 8
Clusterio | playerManager | Downloading Aronak's inventory
Importing inventory before try 8
After import try 8
isPlayerWhitelisted: Aronak try 8
isPlayerWhitelisted done: Aronak try 8
Warning: Inventory syncing slow. Tries: 9
Pooling on 9
Done, pulled ; try 9
Reseting timer try 9
Exited the loop
Pooling on 1
Pooling on 2
Pooling on 3
Pooling on 4
Pooling on 5
Warning: Inventory syncing slow. Tries: 6
Pooling on 6
Warning: Inventory syncing slow. Tries: 7
Pooling on 7
Warning: Inventory syncing slow. Tries: 8
Pooling on 8
Fact: 645.001 Warning ServerSynchronizer.cpp:375: Peer 4 sent IncreasedLatencyConfirm for tick 9714883, but it is too late as I'm processing his tick 9714910
Clusterio | playerManager | 645.001 Warning ServerSynchronizer.cpp:375: Peer 4 sent IncreasedLatencyConfirm for tick 9714883, but it is too late as I'm processing his tick 9714910
/promote xal3xhx
Warning: Inventory syncing slow. Tries: 9
Pooling on 9
Warning: Inventory syncing slow. Tries: 10
Pooling on 10
Warning: Inventory syncing slow. Tries: 11
Pooling on 11
Warning: Inventory syncing slow. Tries: 12
Pooling on 12
Done, pulled ; try 12
Reseting timer try 12
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Pooling on 1
{ ok: false, msg: 'Invalid request parameters' }
Done, pulled ; try 1
Reseting timer try 1
Exited the loop
Syncing done: Aronak try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Done, pulled ; try 0
Reseting timer try 0
Exited the loop
Pooling on 1
Done, pulled ; try 1
Reseting timer try 1
Exited the loop```

### CODE REVIEW

**Comment by Godmave** [comment]
I don't think the return does what you think it does.
It only exists the function and prevents more waiting requests. The interval is still running adding more as soon as the retry-counter gets reset.

**Comment by psihius** [comment]
Watch it :)
You don't see from log, but after the 12 tries, it prints those 0 try like a machine gun that tells me it ends a bunch of them in a one go. There is definitely no delay between those.

**Comment by Hornwitser** [comment]
RCON does not have a throughput limit, clusterio has.  You can run a 100 commands at once over RCON, but due to a bug in Factorio running that many simultaneously is likely to drop players.  Unrelated, but something that might be problematic is that commands can be executed out of order.

**Comment by psihius** [comment]
Well, we can deal with out of order, we are just getting somewhat limited in throughput. But we are looking with @veladon at it and it may be the JS lib's fault and not FActorio's, though maybe pipelining commands into batches and handling response in batches might be a better solution.

**Pull request closed without merging**
